version: '3'

services:
  web:
    build: .
    env_file:
      - .env
    command: sh -c "python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/Tel
      - static_volume:/Tel/staticfiles
      - media_volume:/Tel/mediafiles
    ports:
      - "8000:8000"
    depends_on:
      - tel_db
    restart: always

  tel_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: tel
      POSTGRES_USER: user_tel
      POSTGRES_PASSWORD: password_tel
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always


volumes:
  postgres_data:
  static_volume:
  media_volume:
