# Generated by Django 5.2.3 on 2025-06-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tel_raqam_code', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='request_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
